# A container for solver options
# the top level solver name in brackets should align with the solver name in the config.toml

num_workers = 6

[gurobi]

Method= 2  # Barrier ONLY
Threads= 20  # per solver instance
BarConvTol = 0.05  # Relative Barrier Tolerance primal-dual
# FeasibilityTol= 1e-2  # pretty loose
Crossover= 0  # Disabled
TimeLimit= 18000  # 5 hrs

# regarding BarConvTol:  https://www.gurobi.com/documentation/current/refman/barrier_logging.html
# for records ...
# 'LogFile': './my_gurobi_log.log',
# 'LPWarmStart': 2,  # pass basis

[cbc]
# tbd

[appsi_highs]
# tbd
